import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:somine_app/core/design/design_tokens.dart';
import 'package:somine_app/core/models/item_model.dart';
import 'package:somine_app/core/models/link_preview_model.dart';
import 'package:somine_app/core/providers/auth_providers.dart';
import 'package:somine_app/core/providers/firestore_providers.dart';
import 'package:somine_app/core/services/link_preview_service.dart';
import 'package:somine_app/widgets/loading_indicator.dart';

class CaptureScreen extends ConsumerStatefulWidget {
  final String url;

  const CaptureScreen({super.key, required this.url});

  @override
  ConsumerState<CaptureScreen> createState() => _CaptureScreenState();
}

class _CaptureScreenState extends ConsumerState<CaptureScreen> with SingleTickerProviderStateMixin {
  late TextEditingController _urlController;
  final TextEditingController _noteController = TextEditingController();
  
  String? _selectedCategoryId;
  bool _isSaving = false;
  
  // Animation
  late AnimationController _animController;
  late Animation<double> _scaleAnimation;
  late Animation<double> _opacityAnimation;
  
  // Link Preview State
  bool _isLoadingPreview = false;
  LinkPreviewModel? _previewData;

  @override
  void initState() {
    super.initState();
    _urlController = TextEditingController(text: widget.url);
    
    // Setup Animation
    _animController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 800),
    );

    _scaleAnimation = Tween<double>(begin: 1.0, end: 0.0).animate(
      CurvedAnimation(
        parent: _animController,
        curve: Curves.elasticIn, // Wormhole effect
      ),
    );
    
    _opacityAnimation = Tween<double>(begin: 1.0, end: 0.0).animate(
      CurvedAnimation(
        parent: _animController,
        curve: const Interval(0.5, 1.0, curve: Curves.easeOut),
      ),
    );

    _fetchPreview();
  }

  Future<void> _fetchPreview() async {
    setState(() => _isLoadingPreview = true);
    
    try {
      final data = await LinkPreviewService().fetchPreview(widget.url);
      if (mounted) {
        setState(() {
          _previewData = data;
          _isLoadingPreview = false;
        });
      }
    } catch (e) {
      debugPrint('Error fetching preview: $e');
      if (mounted) {
        setState(() => _isLoadingPreview = false);
      }
    }
  }

  @override
  void dispose() {
    _animController.dispose();
    _urlController.dispose();
    _noteController.dispose();
    super.dispose();
  }

  Future<void> _handleSave() async {
    // 1. Start Animation & Feedback immediately
    HapticFeedback.mediumImpact();
    setState(() => _isSaving = true);
    _animController.forward();

    try {
      // Use Firebase Auth directly instead of Firestore user model
      final user = ref.read(currentUserProvider);
      if (user == null) {
        throw Exception('Lütfen önce giriş yapın');
      }

      final item = ItemModel(
        id: '', // Will be generated by Firestore
        userId: user.uid,
        categoryId: _selectedCategoryId,
        type: ItemType.link,
        url: widget.url,
        // If title is editable, use that, currently not in UI but preview data has it
        ogMetadata: _previewData != null ? OGMetadata(
          title: _previewData!.title,
          description: _previewData!.description,
          imageUrl: _previewData!.imageUrl,
          siteName: _previewData!.siteName,
        ) : null,
        note: _noteController.text.trim().isNotEmpty ? _noteController.text.trim() : null,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // 2. Perform async save
      await ref.read(itemRepositoryProvider).createItem(item);

      // 3. Wait for animation if save was too fast
      if (_animController.isAnimating) {
        await Future.doWhile(() async {
          await Future.delayed(const Duration(milliseconds: 50));
          return _animController.isAnimating;
        });
      }

      if (mounted) {
        setState(() => _isSaving = false);
        Navigator.of(context).pop(); // Close modal
        
        // Success Feedback
        ScaffoldMessenger.of(context).showSnackBar(
           const SnackBar(content: Text('Koleksiyonuna eklendi! ✓')),
        );
      }
    } catch (e) {
      debugPrint('Error saving item: $e');
      // If error, reverse animation to show screen again
      _animController.reverse();
      
      if (mounted) {
        setState(() => _isSaving = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Hata: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black.withValues(alpha: 0.6), // Dimmed background
      body: AnimatedBuilder(
        animation: _animController,
        builder: (context, child) {
          return Transform.scale(
            scale: _scaleAnimation.value,
            child: Opacity(
              opacity: _opacityAnimation.value,
              child: child,
            ),
          );
        },
        child: Center(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(DesignTokens.spacingLG),
              child: Stack(
                children: [
                   // The Modal Card
                   Container(
                     width: double.infinity,
                     constraints: const BoxConstraints(maxWidth: 400),
                     decoration: BoxDecoration(
                       color: DesignTokens.surface,
                       borderRadius: BorderRadius.circular(DesignTokens.radiusXL),
                       boxShadow: DesignTokens.shadowLG,
                     ),
                     clipBehavior: Clip.antiAlias,
                     child: Column(
                       mainAxisSize: MainAxisSize.min,
                       crossAxisAlignment: CrossAxisAlignment.stretch,
                       children: [
                         // Preview Image Header
                         SizedBox(
                           height: 180,
                           child: _isLoadingPreview 
                               ? const Center(child: LoadingIndicator())
                               : _previewData?.imageUrl != null
                                   ? Image.network(
                                       _previewData!.imageUrl!,
                                       fit: BoxFit.cover,
                                       errorBuilder: (_,__,___) => Container(color: DesignTokens.background),
                                     )
                                   : Container(
                                       color: DesignTokens.background,
                                       child: const Icon(Icons.link, size: 48, color: DesignTokens.textTertiary),
                                     ),
                         ),
                         
                         // Content
                         Padding(
                           padding: const EdgeInsets.all(DesignTokens.spacingMD),
                           child: Column(
                             crossAxisAlignment: CrossAxisAlignment.start,
                             children: [
                               if (_previewData?.title != null)
                                 Text(
                                   _previewData!.title!,
                                   style: GoogleFonts.poppins(
                                     fontSize: 16,
                                     fontWeight: FontWeight.bold,
                                     color: DesignTokens.textPrimary,
                                   ),
                                   maxLines: 2,
                                   overflow: TextOverflow.ellipsis,
                                 ),
                                 
                               const SizedBox(height: DesignTokens.spacingMD),
                               
                               // Category Picker (Simple dropdown style or chips)
                               _buildCategorySelector(),
                               
                               const SizedBox(height: DesignTokens.spacingMD),
                               
                               // Note Input
                               TextField(
                                 controller: _noteController,
                                 decoration: InputDecoration(
                                   hintText: 'Bir not ekle...',
                                   hintStyle: GoogleFonts.poppins(color: DesignTokens.textTertiary),
                                   border: OutlineInputBorder(
                                     borderRadius: BorderRadius.circular(DesignTokens.radiusMD),
                                     borderSide: const BorderSide(color: DesignTokens.border),
                                   ),
                                   filled: true,
                                   fillColor: DesignTokens.background,
                                   contentPadding: const EdgeInsets.all(12),
                                 ),
                                 maxLines: 2,
                                 minLines: 1,
                                 style: GoogleFonts.poppins(fontSize: 14),
                               ),
                               
                               const SizedBox(height: DesignTokens.spacingLG),
                               
                               // Actions
                               Row(
                                 children: [
                                   Expanded(
                                     child: TextButton(
                                       onPressed: () => Navigator.pop(context),
                                       child: Text(
                                         'İptal',
                                         style: GoogleFonts.poppins(color: DesignTokens.textSecondary),
                                       ),
                                     ),
                                   ),
                                   const SizedBox(width: 16),
                                   Expanded(
                                     flex: 2,
                                     child: ElevatedButton(
                                       onPressed: _isSaving ? null : _handleSave,
                                       style: ElevatedButton.styleFrom(
                                         backgroundColor: DesignTokens.primary,
                                         foregroundColor: Colors.white,
                                         padding: const EdgeInsets.symmetric(vertical: 16),
                                         shape: RoundedRectangleBorder(
                                           borderRadius: BorderRadius.circular(DesignTokens.radiusLG),
                                         ),
                                         elevation: 0,
                                       ),
                                       child: _isSaving 
                                         ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                                         : Text(
                                             'Kaydet',
                                             style: GoogleFonts.poppins(fontWeight: FontWeight.w600),
                                           ),
                                     ),
                                   ),
                                 ],
                               )
                             ],
                           ),
                         ),
                       ],
                     ),
                   ),
                   
                   // Close Button (Top Right absolute)
                   Positioned(
                     top: 8,
                     right: 8,
                     child: GestureDetector(
                       onTap: () => Navigator.pop(context),
                       child: Container(
                         padding: const EdgeInsets.all(8),
                         decoration: const BoxDecoration(
                           color: Colors.black26,
                           shape: BoxShape.circle,
                         ),
                         child: const Icon(Icons.close, color: Colors.white, size: 20),
                       ),
                     ),
                   ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
  
  Widget _buildCategorySelector() {
    final categoriesAsync = ref.watch(categoriesProvider);
    return categoriesAsync.when(
      data: (categories) {
        if (categories.isEmpty) return const SizedBox.shrink();
        
        return SizedBox(
          height: 36,
          child: ListView.separated(
            scrollDirection: Axis.horizontal,
            itemCount: categories.length,
            separatorBuilder: (_, __) => const SizedBox(width: 8),
            itemBuilder: (context, index) {
              final category = categories[index];
              final isSelected = category.id == _selectedCategoryId;
              return GestureDetector(
                onTap: () => setState(() => _selectedCategoryId = isSelected ? null : category.id),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: isSelected ? DesignTokens.primary : DesignTokens.background,
                    borderRadius: BorderRadius.circular(DesignTokens.radiusFull),
                    border: Border.all(
                      color: isSelected ? DesignTokens.primary : DesignTokens.border,
                    ),
                  ),
                  child: Text(
                    category.name,
                    style: GoogleFonts.poppins(
                      fontSize: 12,
                      color: isSelected ? Colors.white : DesignTokens.textSecondary,
                      fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                    ),
                  ),
                ),
              );
            },
          ),
        );
      },
      loading: () => const SizedBox(height: 36),
      error: (_,__) => const SizedBox.shrink(),
    );
  }
}
